<a href="https://colab.research.google.com/github/FardoZ/Portfolio/blob/main/Data_Lottery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: can you example dataframe by using pandas

import pandas as pd

# Create a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 28],
        'City': ['New York', 'London', 'Paris']}

df = pd.DataFrame(data)

print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   28     Paris

### Install gazpacho first!!

In [ ]:
# prompt: can you web scrap this website "https://www.thairath.co.th/lottery/check?date=2024-03-16" to import only number that this website have by using gazpacho

!pip install gazpacho

from gazpacho import get, Soup

url = "https://www.thairath.co.th/lottery/check?date=2024-03-16"
html = get(url)
soup = Soup(html)

# Assuming the lottery numbers are within elements with a specific class or tag
# Adjust the following code based on the website's HTML structure
lottery_numbers = soup.find('div', {"class" :"css-1njvt94 efr6tej12"})  # Replace with the appropriate tag and class

print(lottery_numbers)

Collecting gazpacho
  Downloading gazpacho-1.1.tar.gz (7.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: gazpacho
  Building wheel for gazpacho (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7460 sha256=e627a122dce9c936957e8c118bb051ca3665775d9f5498d6a71e668863903f03
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho
Installing collected packages: gazpacho
Successfully installed gazpacho-1.1
Lottery numbers not found.

In [1]:
!pip install gazpacho

Collecting gazpacho
  Downloading gazpacho-1.1.tar.gz (7.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: gazpacho
  Building wheel for gazpacho (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7461 sha256=73353329688cd4fd9d597146151bc2840e40546fa67f527515078c3da51a6e79
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho
Installing collected packages: gazpacho
Successfully installed gazpacho-1.1

In [ ]:
url = "https://www.thairath.co.th/lottery/check?date=2024-03-16"
html = get(url)
soup = Soup(html)

# Assuming the lottery numbers are within elements with a specific class or tag
# Adjust the following code based on the website's HTML structure
lottery_numbers = soup.find('div', attrs = {"class" :"__result_five css-ph82nd ecgl95t10"})  # Replace with the appropriate tag and class
lt_test_1 = soup.find('p' ,{'class' :"css-pnpogb ecgl95t18"})

print(lt_test_1)

[<p class="css-pnpogb ecgl95t18">485642</p>, <p class="css-pnpogb ecgl95t18">631001</p>, <p class="css-pnpogb ecgl95t18">897694</p>, <p class="css-pnpogb ecgl95t18">158908</p>, <p class="css-pnpogb ecgl95t18">485546</p>, <p class="css-pnpogb ecgl95t18">935199</p>, <p class="css-pnpogb ecgl95t18">322578</p>, <p class="css-pnpogb ecgl95t18">669775</p>, <p class="css-pnpogb ecgl95t18">620048</p>, <p class="css-pnpogb ecgl95t18">826842</p>, <p class="css-pnpogb ecgl95t18">421546</p>, <p class="css-pnpogb ecgl95t18">105303</p>, <p class="css-pnpogb ecgl95t18">951264</p>, <p class="css-pnpogb ecgl95t18">238160</p>, <p class="css-pnpogb ecgl95t18">696050</p>, <p class="css-pnpogb ecgl95t18">758395</p>, <p class="css-pnpogb ecgl95t18">000341</p>, <p class="css-pnpogb ecgl95t18">531222</p>, <p class="css-pnpogb ecgl95t18">431579</p>, <p class="css-pnpogb ecgl95t18">382805</p>, <p class="css-pnpogb ecgl95t18">411596</p>, <p class="css-pnpogb ecgl95t18">246073</p>, <p class="css-pnpogb ecgl95t18">447454</p>, <p class="css-pnpogb ecgl95t18">535126</p>, <p class="css-pnpogb ecgl95t18">791580</p>, <p class="css-pnpogb ecgl95t18">657195</p>, <p class="css-pnpogb ecgl95t18">720975</p>, <p class="css-pnpogb ecgl95t18">434148</p>, <p class="css-pnpogb ecgl95t18">281788</p>, <p class="css-pnpogb ecgl95t18">118769</p>, <p class="css-pnpogb ecgl95t18">018003</p>, <p class="css-pnpogb ecgl95t18">363379</p>, <p class="css-pnpogb ecgl95t18">611287</p>, <p class="css-pnpogb ecgl95t18">236153</p>, <p class="css-pnpogb ecgl95t18">542218</p>, <p class="css-pnpogb ecgl95t18">667327</p>, <p class="css-pnpogb ecgl95t18">258455</p>, <p class="css-pnpogb ecgl95t18">716354</p>, <p class="css-pnpogb ecgl95t18">766185</p>, <p class="css-pnpogb ecgl95t18">323851</p>, <p class="css-pnpogb ecgl95t18">766682</p>, <p class="css-pnpogb ecgl95t18">990089</p>, <p class="css-pnpogb ecgl95t18">343639</p>, <p class="css-pnpogb ecgl95t18">835813</p>, <p class="css-pnpogb ecgl95t18">051048</p>, <p class="css-pnpogb ecgl95t18">186506</p>, <p class="css-pnpogb ecgl95t18">621447</p>, <p class="css-pnpogb ecgl95t18">836291</p>, <p class="css-pnpogb ecgl95t18">194519</p>, <p class="css-pnpogb ecgl95t18">429726</p>, <p class="css-pnpogb ecgl95t18">024292</p>, <p class="css-pnpogb ecgl95t18">511125</p>, <p class="css-pnpogb ecgl95t18">229005</p>, <p class="css-pnpogb ecgl95t18">465714</p>, <p class="css-pnpogb ecgl95t18">656833</p>, <p class="css-pnpogb ecgl95t18">830148</p>, <p class="css-pnpogb ecgl95t18">369148</p>, <p class="css-pnpogb ecgl95t18">381682</p>, <p class="css-pnpogb ecgl95t18">701512</p>, <p class="css-pnpogb ecgl95t18">082645</p>, <p class="css-pnpogb ecgl95t18">069735</p>, <p class="css-pnpogb ecgl95t18">636604</p>, <p class="css-pnpogb ecgl95t18">788574</p>, <p class="css-pnpogb ecgl95t18">582288</p>, <p class="css-pnpogb ecgl95t18">941507</p>, <p class="css-pnpogb ecgl95t18">897221</p>, <p class="css-pnpogb ecgl95t18">359981</p>, <p class="css-pnpogb ecgl95t18">281316</p>, <p class="css-pnpogb ecgl95t18">483750</p>, <p class="css-pnpogb ecgl95t18">790445</p>, <p class="css-pnpogb ecgl95t18">703954</p>, <p class="css-pnpogb ecgl95t18">941330</p>, <p class="css-pnpogb ecgl95t18">777286</p>, <p class="css-pnpogb ecgl95t18">834119</p>, <p class="css-pnpogb ecgl95t18">089496</p>, <p class="css-pnpogb ecgl95t18">256562</p>, <p class="css-pnpogb ecgl95t18">241656</p>, <p class="css-pnpogb ecgl95t18">726226</p>, <p class="css-pnpogb ecgl95t18">827733</p>, <p class="css-pnpogb ecgl95t18">733185</p>, <p class="css-pnpogb ecgl95t18">769325</p>, <p class="css-pnpogb ecgl95t18">793922</p>, <p class="css-pnpogb ecgl95t18">494870</p>, <p class="css-pnpogb ecgl95t18">123872</p>, <p class="css-pnpogb ecgl95t18">505629</p>, <p class="css-pnpogb ecgl95t18">952154</p>, <p class="css-pnpogb ecgl95t18">421006</p>, <p class="css-pnpogb ecgl95t18">208031</p>, <p class="css-pnpogb ecgl95t18">072364</p>, <p class="css-pnpogb ecgl95t18">229601</p>, <p class="css-pnpogb ecgl95t18">263497</p>, <p class="css-pnpogb ecgl95t18">074037</p>, <p class="css-pnpogb ecgl95t18">061993</p>, <p class="css-pnpogb ecgl95t18">366058</p>, <p class="css-pnpogb ecgl95t18">321698</p>, <p class="css-pnpogb ecgl95t18">528251</p>, <p class="css-pnpogb ecgl95t18">942827</p>, <p class="css-pnpogb ecgl95t18">074356</p>, <p class="css-pnpogb ecgl95t18">067668</p>, <p class="css-pnpogb ecgl95t18">615908</p>, <p class="css-pnpogb ecgl95t18">155537</p>, <p class="css-pnpogb ecgl95t18">414317</p>, <p class="css-pnpogb ecgl95t18">405975</p>, <p class="css-pnpogb ecgl95t18">763641</p>, <p class="css-pnpogb ecgl95t18">111550</p>, <p class="css-pnpogb ecgl95t18">638069</p>, <p class="css-pnpogb ecgl95t18">530904</p>, <p class="css-pnpogb ecgl95t18">349703</p>, <p class="css-pnpogb ecgl95t18">937154</p>, <p class="css-pnpogb ecgl95t18">075430</p>, <p class="css-pnpogb ecgl95t18">779987</p>, <p class="css-pnpogb ecgl95t18">843878</p>, <p class="css-pnpogb ecgl95t18">392798</p>, <p class="css-pnpogb ecgl95t18">257097</p>, <p class="css-pnpogb ecgl95t18">912304</p>, <p class="css-pnpogb ecgl95t18">894675</p>, <p class="css-pnpogb ecgl95t18">706515</p>, <p class="css-pnpogb ecgl95t18">427954</p>, <p class="css-pnpogb ecgl95t18">538263</p>, <p class="css-pnpogb ecgl95t18">979750</p>, <p class="css-pnpogb ecgl95t18">711328</p>, <p class="css-pnpogb ecgl95t18">981529</p>, <p class="css-pnpogb ecgl95t18">898338</p>, <p class="css-pnpogb ecgl95t18">803122</p>, <p class="css-pnpogb ecgl95t18">305480</p>, <p class="css-pnpogb ecgl95t18">754334</p>, <p class="css-pnpogb ecgl95t18">929805</p>, <p class="css-pnpogb ecgl95t18">613167</p>, <p class="css-pnpogb ecgl95t18">926111</p>, <p class="css-pnpogb ecgl95t18">384858</p>, <p class="css-pnpogb ecgl95t18">668676</p>, <p class="css-pnpogb ecgl95t18">779577</p>, <p class="css-pnpogb ecgl95t18">253377</p>, <p class="css-pnpogb ecgl95t18">712705</p>, <p class="css-pnpogb ecgl95t18">382576</p>, <p class="css-pnpogb ecgl95t18">197338</p>, <p class="css-pnpogb ecgl95t18">291923</p>, <p class="css-pnpogb ecgl95t18">580053</p>, <p class="css-pnpogb ecgl95t18">152229</p>, <p class="css-pnpogb ecgl95t18">250163</p>, <p class="css-pnpogb ecgl95t18">022080</p>, <p class="css-pnpogb ecgl95t18">372465</p>, <p class="css-pnpogb ecgl95t18">077241</p>, <p class="css-pnpogb ecgl95t18">351806</p>, <p class="css-pnpogb ecgl95t18">270058</p>, <p class="css-pnpogb ecgl95t18">341652</p>, <p class="css-pnpogb ecgl95t18">765794</p>, <p class="css-pnpogb ecgl95t18">346588</p>, <p class="css-pnpogb ecgl95t18">640404</p>, <p class="css-pnpogb ecgl95t18">950507</p>, <p class="css-pnpogb ecgl95t18">124680</p>, <p class="css-pnpogb ecgl95t18">554182</p>, <p class="css-pnpogb ecgl95t18">212559</p>, <p class="css-pnpogb ecgl95t18">570696</p>, <p class="css-pnpogb ecgl95t18">574568</p>, <p class="css-pnpogb ecgl95t18">001197</p>, <p class="css-pnpogb ecgl95t18">478627</p>, <p class="css-pnpogb ecgl95t18">007809</p>, <p class="css-pnpogb ecgl95t18">132215</p>, <p class="css-pnpogb ecgl95t18">512054</p>, <p class="css-pnpogb ecgl95t18">269609</p>, <p class="css-pnpogb ecgl95t18">943540</p>, <p class="css-pnpogb ecgl95t18">372430</p>, <p class="css-pnpogb ecgl95t18">259872</p>, <p class="css-pnpogb ecgl95t18">086935</p>]

In [ ]:
import pandas as pd
from gazpacho import get, Soup

url = "https://www.thairath.co.th/lottery/check?date=2024-03-16"
html = get(url)
soup = Soup(html)

# Find the <p> element with the specified class
elements = soup.find('p', {'class': 'css-pnpogb ecgl95t18'})

if isinstance(elements, list):
    for element in elements:
        lottery_number = element.text
        # Create a dictionary to store the lottery number with separate positions
        lottery_data = {'1': lottery_number[0],
                         '2': lottery_number[1],
                         '3': lottery_number[2],
                         '4': lottery_number[3],
                         '5': lottery_number[4],
                         '6': lottery_number[5]}
        # Create a DataFrame from the dictionary
        df = pd.DataFrame(lottery_data, index=[0])
        print(df)
else:
    lottery_number = elements.text
    # Create a dictionary to store the lottery number with separate positions
    lottery_data = {'1': lottery_number[0],
                     '2': lottery_number[1],
                     '3': lottery_number[2],
                     '4': lottery_number[3],
                     '5': lottery_number[4],
                     '6': lottery_number[5]}
    # Create a DataFrame from the dictionary
    df = pd.DataFrame(lottery_data, index=[0])
    print(df)

   1  2  3  4  5  6
0  4  8  5  6  4  2
   1  2  3  4  5  6
0  6  3  1  0  0  1
   1  2  3  4  5  6
0  8  9  7  6  9  4
   1  2  3  4  5  6
0  1  5  8  9  0  8
   1  2  3  4  5  6
0  4  8  5  5  4  6
   1  2  3  4  5  6
0  9  3  5  1  9  9
   1  2  3  4  5  6
0  3  2  2  5  7  8
   1  2  3  4  5  6
0  6  6  9  7  7  5
   1  2  3  4  5  6
0  6  2  0  0  4  8
   1  2  3  4  5  6
0  8  2  6  8  4  2
   1  2  3  4  5  6
0  4  2  1  5  4  6
   1  2  3  4  5  6
0  1  0  5  3  0  3
   1  2  3  4  5  6
0  9  5  1  2  6  4
   1  2  3  4  5  6
0  2  3  8  1  6  0
   1  2  3  4  5  6
0  6  9  6  0  5  0
   1  2  3  4  5  6
0  7  5  8  3  9  5
   1  2  3  4  5  6
0  0  0  0  3  4  1
   1  2  3  4  5  6
0  5  3  1  2  2  2
   1  2  3  4  5  6
0  4  3  1  5  7  9
   1  2  3  4  5  6
0  3  8  2  8  0  5
   1  2  3  4  5  6
0  4  1  1  5  9  6
   1  2  3  4  5  6
0  2  4  6  0  7  3
   1  2  3  4  5  6
0  4  4  7  4  5  4
   1  2  3  4  5  6
0  5  3  5  1  2  6
   1  2  3  4  5  6
0  7  9  1  5  8  0
   1  2  3  4  5  6
0  6  5  7  1  9  5
   1  2  3  4  5  6
0  7  2  0  9  7  5
   1  2  3  4  5  6
0  4  3  4  1  4  8
   1  2  3  4  5  6
0  2  8  1  7  8  8
   1  2  3  4  5  6
0  1  1  8  7  6  9
   1  2  3  4  5  6
0  0  1  8  0  0  3
   1  2  3  4  5  6
0  3  6  3  3  7  9
   1  2  3  4  5  6
0  6  1  1  2  8  7
   1  2  3  4  5  6
0  2  3  6  1  5  3
   1  2  3  4  5  6
0  5  4  2  2  1  8
   1  2  3  4  5  6
0  6  6  7  3  2  7
   1  2  3  4  5  6
0  2  5  8  4  5  5
   1  2  3  4  5  6
0  7  1  6  3  5  4
   1  2  3  4  5  6
0  7  6  6  1  8  5
   1  2  3  4  5  6
0  3  2  3  8  5  1
   1  2  3  4  5  6
0  7  6  6  6  8  2
   1  2  3  4  5  6
0  9  9  0  0  8  9
   1  2  3  4  5  6
0  3  4  3  6  3  9
   1  2  3  4  5  6
0  8  3  5  8  1  3
   1  2  3  4  5  6
0  0  5  1  0  4  8
   1  2  3  4  5  6
0  1  8  6  5  0  6
   1  2  3  4  5  6
0  6  2  1  4  4  7
   1  2  3  4  5  6
0  8  3  6  2  9  1
   1  2  3  4  5  6
0  1  9  4  5  1  9
   1  2  3  4  5  6
0  4  2  9  7  2  6
   1  2  3  4  5  6
0  0  2  4  2  9  2
   1  2  3  4  5  6
0  5  1  1  1  2  5
   1  2  3  4  5  6
0  2  2  9  0  0  5
   1  2  3  4  5  6
0  4  6  5  7  1  4
   1  2  3  4  5  6
0  6  5  6  8  3  3
   1  2  3  4  5  6
0  8  3  0  1  4  8
   1  2  3  4  5  6
0  3  6  9  1  4  8
   1  2  3  4  5  6
0  3  8  1  6  8  2
   1  2  3  4  5  6
0  7  0  1  5  1  2
   1  2  3  4  5  6
0  0  8  2  6  4  5
   1  2  3  4  5  6
0  0  6  9  7  3  5
   1  2  3  4  5  6
0  6  3  6  6  0  4
   1  2  3  4  5  6
0  7  8  8  5  7  4
   1  2  3  4  5  6
0  5  8  2  2  8  8
   1  2  3  4  5  6
0  9  4  1  5  0  7
   1  2  3  4  5  6
0  8  9  7  2  2  1
   1  2  3  4  5  6
0  3  5  9  9  8  1
   1  2  3  4  5  6
0  2  8  1  3  1  6
   1  2  3  4  5  6
0  4  8  3  7  5  0
   1  2  3  4  5  6
0  7  9  0  4  4  5
   1  2  3  4  5  6
0  7  0  3  9  5  4
   1  2  3  4  5  6
0  9  4  1  3  3  0
   1  2  3  4  5  6
0  7  7  7  2  8  6
   1  2  3  4  5  6
0  8  3  4  1  1  9
   1  2  3  4  5  6
0  0  8  9  4  9  6
   1  2  3  4  5  6
0  2  5  6  5  6  2
   1  2  3  4  5  6
0  2  4  1  6  5  6
   1  2  3  4  5  6
0  7  2  6  2  2  6
   1  2  3  4  5  6
0  8  2  7  7  3  3
   1  2  3  4  5  6
0  7  3  3  1  8  5
   1  2  3  4  5  6
0  7  6  9  3  2  5
   1  2  3  4  5  6
0  7  9  3  9  2  2
   1  2  3  4  5  6
0  4  9  4  8  7  0
   1  2  3  4  5  6
0  1  2  3  8  7  2
   1  2  3  4  5  6
0  5  0  5  6  2  9
   1  2  3  4  5  6
0  9  5  2  1  5  4
   1  2  3  4  5  6
0  4  2  1  0  0  6
   1  2  3  4  5  6
0  2  0  8  0  3  1
   1  2  3  4  5  6
0  0  7  2  3  6  4
   1  2  3  4  5  6
0  2  2  9  6  0  1
   1  2  3  4  5  6
0  2  6  3  4  9  7
   1  2  3  4  5  6
0  0  7  4  0  3  7
   1  2  3  4  5  6
0  0  6  1  9  9  3
   1  2  3  4  5  6
0  3  6  6  0  5  8
   1  2  3  4  5  6
0  3  2  1  6  9  8
   1  2  3  4  5  6
0  5  2  8  2  5  1
   1  2  3  4  5  6
0  9  4  2  8  2  7
   1  2  3  4  5  6
0  0  7  4  3  5  6
   1  2  3  4  5  6
0  0  6  7  6  6  8
   1  2  3  4  5  6
0  6  1  5  9  0  8
   1  2  3  4  5  6
0  1  5  5  5  3  7
   1  2  3  4  5  6
0  4  1  4  3  1  7
   1  2  3  4  5  6
0  4  0  5  9  7  5
   1  2  3  4  5  6
0  7  6  3  6  4  1
   1  2  3  4  5  6
0  1  1  1  5  5  0
   1  2  3  4  5  6
0  6  3  8  0  6  9
   1  2  3  4  5  6
0  5  3  0  9  0  4
   1  2  3  4  5  6
0  3  4  9  7  0  3
   1  2  3  4  5  6
0  9  3  7  1  5  4
   1  2  3  4  5  6
0  0  7  5  4  3  0
   1  2  3  4  5  6
0  7  7  9  9  8  7
   1  2  3  4  5  6
0  8  4  3  8  7  8
   1  2  3  4  5  6
0  3  9  2  7  9  8
   1  2  3  4  5  6
0  2  5  7  0  9  7
   1  2  3  4  5  6
0  9  1  2  3  0  4
   1  2  3  4  5  6
0  8  9  4  6  7  5
   1  2  3  4  5  6
0  7  0  6  5  1  5
   1  2  3  4  5  6
0  4  2  7  9  5  4
   1  2  3  4  5  6
0  5  3  8  2  6  3
   1  2  3  4  5  6
0  9  7  9  7  5  0
   1  2  3  4  5  6
0  7  1  1  3  2  8
   1  2  3  4  5  6
0  9  8  1  5  2  9
   1  2  3  4  5  6
0  8  9  8  3  3  8
   1  2  3  4  5  6
0  8  0  3  1  2  2
   1  2  3  4  5  6
0  3  0  5  4  8  0
   1  2  3  4  5  6
0  7  5  4  3  3  4
   1  2  3  4  5  6
0  9  2  9  8  0  5
   1  2  3  4  5  6
0  6  1  3  1  6  7
   1  2  3  4  5  6
0  9  2  6  1  1  1
   1  2  3  4  5  6
0  3  8  4  8  5  8
   1  2  3  4  5  6
0  6  6  8  6  7  6
   1  2  3  4  5  6
0  7  7  9  5  7  7
   1  2  3  4  5  6
0  2  5  3  3  7  7
   1  2  3  4  5  6
0  7  1  2  7  0  5
   1  2  3  4  5  6
0  3  8  2  5  7  6
   1  2  3  4  5  6
0  1  9  7  3  3  8
   1  2  3  4  5  6
0  2  9  1  9  2  3
   1  2  3  4  5  6
0  5  8  0  0  5  3
   1  2  3  4  5  6
0  1  5  2  2  2  9
   1  2  3  4  5  6
0  2  5  0  1  6  3
   1  2  3  4  5  6
0  0  2  2  0  8  0
   1  2  3  4  5  6
0  3  7  2  4  6  5
   1  2  3  4  5  6
0  0  7  7  2  4  1
   1  2  3  4  5  6
0  3  5  1  8  0  6
   1  2  3  4  5  6
0  2  7  0  0  5  8
   1  2  3  4  5  6
0  3  4  1  6  5  2
   1  2  3  4  5  6
0  7  6  5  7  9  4
   1  2  3  4  5  6
0  3  4  6  5  8  8
   1  2  3  4  5  6
0  6  4  0  4  0  4
   1  2  3  4  5  6
0  9  5  0  5  0  7
   1  2  3  4  5  6
0  1  2  4  6  8  0
   1  2  3  4  5  6
0  5  5  4  1  8  2
   1  2  3  4  5  6
0  2  1  2  5  5  9
   1  2  3  4  5  6
0  5  7  0  6  9  6
   1  2  3  4  5  6
0  5  7  4  5  6  8
   1  2  3  4  5  6
0  0  0  1  1  9  7
   1  2  3  4  5  6
0  4  7  8  6  2  7
   1  2  3  4  5  6
0  0  0  7  8  0  9
   1  2  3  4  5  6
0  1  3  2  2  1  5
   1  2  3  4  5  6
0  5  1  2  0  5  4
   1  2  3  4  5  6
0  2  6  9  6  0  9
   1  2  3  4  5  6
0  9  4  3  5  4  0
   1  2  3  4  5  6
0  3  7  2  4  3  0
   1  2  3  4  5  6
0  2  5  9  8  7  2
   1  2  3  4  5  6
0  0  8  6  9  3  5

##TEST SECTION AND FORMAT CODE FOR WEB SCARP SECTION

In [ ]:
## test 101
import pandas as pd
from gazpacho import get, Soup

url = "https://www.thairath.co.th/lottery/check?date=2024-03-16"
html = get(url)
soup = Soup(html)

# Find the <p> element with the specified class
elements = soup.find('p', {'class': 'css-pnpogb ecgl95t18'})

all_lottery_data = [] # Create a list to store all lottery data

for element in elements:
        lottery_number = element.text
        # Create a dictionary to store the lottery number with separate positions
        lottery_data = {'1': lottery_number[0],
                        '2': lottery_number[1],
                        '3': lottery_number[2],
                        '4': lottery_number[3],
                        '5': lottery_number[4],
                        '6': lottery_number[5]}

        all_lottery_data.append(lottery_data) # Append each lottery_data to the list


df = pd.DataFrame(all_lottery_data) # Create the DataFrame outside the loop
print(df)
df.to_csv('lottery_numbers.csv', index=False)

     1  2  3  4  5  6
0    4  8  5  6  4  2
1    6  3  1  0  0  1
2    8  9  7  6  9  4
3    1  5  8  9  0  8
4    4  8  5  5  4  6
..  .. .. .. .. .. ..
160  2  6  9  6  0  9
161  9  4  3  5  4  0
162  3  7  2  4  3  0
163  2  5  9  8  7  2
164  0  8  6  9  3  5

[165 rows x 6 columns]

In [ ]:
## Test 102
import pandas as pd
from gazpacho import get, Soup

url = "https://www.thairath.co.th/lottery/check?date=2024-03-16"
html = get(url)
soup = Soup(html)

# Find the <p> element with the specified class
elements = soup.find('p', {'class': "css-jf9pru ecgl95t12"})

# Counter for the loop
count = 0

for element in elements:
    lottery_number = element.text

    if count < 2:
        # Add "0" after the number
        modified_number = lottery_number + "000"
        count += 1
    else:
        # Use zfill(6)
        modified_number = lottery_number.zfill(6)

    lottery_data_2 = {'1': modified_number[0],
                    '2': modified_number[1],
                    '3': modified_number[2],
                    '4': modified_number[3],
                    '5': modified_number[4],
                    '6': modified_number[5]}
    print(pd.DataFrame(lottery_data_2, index =[0]))
    all_lottery_data.append(lottery_data_2)

   1  2  3  4  5  6
0  5  7  1  0  0  0
   1  2  3  4  5  6
0  5  0  9  0  0  0
   1  2  3  4  5  6
0  0  0  0  7  9  4
   1  2  3  4  5  6
0  0  0  0  3  2  9
   1  2  3  4  5  6
0  9  9  7  6  2  5
   1  2  3  4  5  6
0  9  9  7  6  2  7

In [ ]:
## Test 103
import pandas as pd
from gazpacho import get, Soup

url = "https://www.thairath.co.th/lottery/check?date=2024-03-16"
html = get(url)
soup = Soup(html)

# Find the <p> element with the specified class
elements = soup.find('p', {'class': "css-1uk1gs8 ecgl95t7"})

lottery_number = ""  # Initialize an empty string to store the combined numbers

for element in elements:
    lottery_number += element.text  # Concatenate the numbers from each element

# Corrected indentation for the following block
lottery_data_3 = {'1': lottery_number[0],
                  '2': lottery_number[1],
                  '3': lottery_number[2],
                  '4': lottery_number[3],
                  '5': lottery_number[4],
                  '6': lottery_number[5]}
all_lottery_data.append(lottery_data_3)
print(lottery_number)

997626

In [ ]:
## Test 103
import pandas as pd
from gazpacho import get, Soup

url = "https://www.thairath.co.th/lottery/check?date=2024-03-16"
html = get(url)
soup = Soup(html)

# Find the <p> element with the specified class
elements = soup.find('p', {'class': "css-1uk1gs8 ecgl95t7"})
for element in elements:
    lottery_number = element.text
    print(lottery_number)

9
9
7
6
2
6

## Here How to combine dataframe

In [ ]:
#Test combine dataframe
## Prep Update Data
new_lottery_data = []
import pandas as pd
from gazpacho import get, Soup

url = "https://www.thairath.co.th/lottery/check?date=2024-10-01"
html = get(url)
soup = Soup(html)
# Find the <p> element with the specified class
elements = soup.find('p', {'class': 'css-pnpogb ecgl95t18'})

for element in elements:
        lottery_number = element.text
        # Create a dictionary to store the lottery number with separate positions
        lottery_data = {'1': lottery_number[0],
                        '2': lottery_number[1],
                        '3': lottery_number[2],
                        '4': lottery_number[3],
                        '5': lottery_number[4],
                        '6': lottery_number[5]}

        new_lottery_data.append(lottery_data) # Append each lottery_data to the list

elements = soup.find('p', {'class': "css-jf9pru ecgl95t12"})

# Counter for the loop
count = 0

for element in elements:
    lottery_number = element.text

    if count < 2:
        # Add "0" after the number
        modified_number = lottery_number + "000"
        count += 1
    else:
        # Use zfill(6)
        modified_number = lottery_number.zfill(6)

    lottery_data_2 = {'1': modified_number[0],
                    '2': modified_number[1],
                    '3': modified_number[2],
                    '4': modified_number[3],
                    '5': modified_number[4],
                    '6': modified_number[5]}

    new_lottery_data.append(lottery_data_2)
elements = soup.find('p', {'class': "css-1uk1gs8 ecgl95t7"})

lottery_number = ""  # Initialize an empty string to store the combined numbers

for element in elements:
    lottery_number += element.text  # Concatenate the numbers from each element

# Corrected indentation for the following block
lottery_data_3 = {'1': lottery_number[0],
                  '2': lottery_number[1],
                  '3': lottery_number[2],
                  '4': lottery_number[3],
                  '5': lottery_number[4],
                  '6': lottery_number[5]}
new_lottery_data.append(lottery_data_3)
##View df section
df = pd.DataFrame(new_lottery_data) # Create the DataFrame outside the loop
print(df)
df.to_csv('Update_lottery_numbers.csv', index=False)

     1  2  3  4  5  6
0    6  1  8  3  0  4
1    7  0  6  5  7  0
2    9  2  0  2  1  2
3    6  1  9  4  5  7
4    8  0  3  1  8  6
..  .. .. .. .. .. ..
167  0  0  0  0  7  9
168  0  0  0  5  6  6
169  7  1  8  6  6  4
170  7  1  8  6  6  6
171  7  1  8  6  6  5

[172 rows x 6 columns]

In [ ]:
## Here! is How to combines dataframe
df_combined = pd.concat([df,DF_data_lottery], ignore_index=True)
print(df_combined)

       1  2  3  4  5  6
0      6  1  8  3  0  4
1      7  0  6  5  7  0
2      9  2  0  2  1  2
3      6  1  9  4  5  7
4      8  0  3  1  8  6
...   .. .. .. .. .. ..
23387  0  0  0  7  0  1
23388  0  0  0  8  8  4
23389  7  3  5  8  6  6
23390  7  3  5  8  6  8
23391  7  3  5  8  6  7

[23392 rows x 6 columns]

In [ ]:
#update to new dataset lottery
df_combined.to_csv('prep_lottery_numbers.csv', index=False)

## Prep Data For Machine Learning

In [ ]:
## เข้ามาให้รันตัวนี้ก่อนแล้วค่อยไปแก้เลขหน้า
import pandas as pd
import numpy as np
df_combined = pd.read_csv('prep_lottery_numbersV1.csv')
Df = df_combined
print(Df)

       1  2  3  4  5  6        date  6_number  Draw winning 2 winning 3  \
0      6  1  8  3  0  4  2024-10-01    618304     1    618304         -
1      7  0  6  5  7  0  2024-10-01    706570     1    706570         -
2      9  2  0  2  1  2  2024-10-01    920212     1    920212         -
3      6  1  9  4  5  7  2024-10-01    619457     1    619457         -
4      8  0  3  1  8  6  2024-10-01    803186     1    803186         -
...   .. .. .. .. .. ..         ...       ...   ...       ...       ...
23387  0  0  0  7  0  1  2018-11-02       701   136         -         -
23388  0  0  0  8  8  4  2018-11-02       884   136         -         -
23389  7  3  5  8  6  6  2018-11-02    735866   136         -         -
23390  7  3  5  8  6  8  2018-11-02    735868   136         -         -
23391  7  3  5  8  6  7  2018-11-02    735867   136         -         -

      winning 4 winning 5 winning 1 winning 1 คล้าย
0             -         -         -               -
1             -         -         -               -
2             -         -         -               -
3             -         -         -               -
4             -         -         -               -
...         ...       ...       ...             ...
23387         -         -         -               -
23388         -         -         -               -
23389         -         -         -          735866
23390         -         -         -          735868
23391         -         -    735867               -

[23392 rows x 15 columns]

In [ ]:
# Concatenate the columns and create the '6_number' column in the original DataFrame
df_combined['6_number'] = df_combined['1'].astype(str).str.zfill(1) + df_combined['2'].astype(str) + df_combined['3'].astype(str) + \
                             df_combined['4'].astype(str) + df_combined['5'].astype(str) + df_combined['6'].astype(str)
print(df_combined)

       1  2  3  4  5  6        date 6_number  Draw winning 2 winning 3  \
0      6  1  8  3  0  4  2024-10-01   618304     1    618304         -
1      7  0  6  5  7  0  2024-10-01   706570     1    706570         -
2      9  2  0  2  1  2  2024-10-01   920212     1    920212         -
3      6  1  9  4  5  7  2024-10-01   619457     1    619457         -
4      8  0  3  1  8  6  2024-10-01   803186     1    803186         -
...   .. .. .. .. .. ..         ...      ...   ...       ...       ...
23387  0  0  0  7  0  1  2018-11-02   000701   136         -         -
23388  0  0  0  8  8  4  2018-11-02   000884   136         -         -
23389  7  3  5  8  6  6  2018-11-02   735866   136         -         -
23390  7  3  5  8  6  8  2018-11-02   735868   136         -         -
23391  7  3  5  8  6  7  2018-11-02   735867   136         -         -

      winning 4 winning 5 winning 1 winning 1 คล้าย
0             -         -         -               -
1             -         -         -               -
2             -         -         -               -
3             -         -         -               -
4             -         -         -               -
...         ...       ...       ...             ...
23387         -         -         -               -
23388         -         -         -               -
23389         -         -         -          735866
23390         -         -         -          735868
23391         -         -    735867               -

[23392 rows x 15 columns]

In [ ]:
import pandas as pd

# Assuming your DataFrame is named df_combined

# Calculate the number of days to go back
days_to_go_back = len(df_combined) // 172

# Create a list of dates counting down
dates = pd.date_range('2024-10-01', periods=days_to_go_back, freq='-16D')

# Repeat each date 172 times
date_column = dates.repeat(172)

# Add the date column to the DataFrame
df_combined['date'] = date_column

# Group the DataFrame by the date column จะอยุ่หลังสุดเวลา prep data เสมอ
grouped_df = df_combined.groupby('date')

print(grouped_df)
grouped_df.head()

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7b0b2a011000>

       1  2  3  4  5  6       date  6_number  Draw
0      6  1  8  3  0  4 2024-10-01    618304     1
1      7  0  6  5  7  0 2024-10-01    706570     1
2      9  2  0  2  1  2 2024-10-01    920212     1
3      6  1  9  4  5  7 2024-10-01    619457     1
4      8  0  3  1  8  6 2024-10-01    803186     1
...   .. .. .. .. .. ..        ...       ...   ...
23220  8  3  8  2  6  2 2018-11-02    838262   136
23221  0  3  1  8  8  0 2018-11-02     31880   136
23222  4  6  6  1  8  2 2018-11-02    466182   136
23223  5  4  8  0  9  7 2018-11-02    548097   136
23224  9  9  0  8  2  4 2018-11-02    990824   136

[680 rows x 9 columns]

In [ ]:
df_combined['Draw'] = (df_combined.index // 172) + 1

In [ ]:
df_combined['date'] = date_column

In [ ]:
#อันนี้คือแยกรางวัลที่ 2
import pandas as pd

# Assuming your DataFrame is named df_combined

# Create the 'winning 2' column if it doesn't exist
if 'winning 2' not in df_combined.columns:
  df_combined['winning 2'] = ''

for i in range(0, len(df_combined), 172):
  # Copy the first 5 values of '6_number' to 'winning 2' for the current group
  df_combined.iloc[i:i+5, df_combined.columns.get_loc('winning 2')] = df_combined.iloc[i:i+5]['6_number'].values

  # Set 'winning 2' to '-' for rows that are not in the top 5 of the group
  df_combined.iloc[i+5:i+172, df_combined.columns.get_loc('winning 2')] = '-'

# Print the updated DataFrame
print(df_combined[0:5])

   1  2  3  4  5  6       date 6_number  Draw winning 2
0  6  1  8  3  0  4 2024-10-01   618304     1    618304
1  7  0  6  5  7  0 2024-10-01   706570     1    706570
2  9  2  0  2  1  2 2024-10-01   920212     1    920212
3  6  1  9  4  5  7 2024-10-01   619457     1    619457
4  8  0  3  1  8  6 2024-10-01   803186     1    803186

In [ ]:
#อันนี้คือแยกรางวัลที่ 3
import pandas as pd

# Assuming your DataFrame is named df_combined

# Create the 'winning 2' column if it doesn't exist
if 'winning 3' not in df_combined.columns:
  df_combined['winning 3'] = ''

for i in range(0, len(df_combined), 172):
  df_combined.iloc[i:i+5, df_combined.columns.get_loc('winning 3')] = '-'
  #The following line was not indented correctly and has been fixed.
  df_combined.iloc[i+5:i+15, df_combined.columns.get_loc('winning 3')] = df_combined.iloc[i+5:i+15]['6_number'].values

  # Set 'winning 2' to '-' for rows that are not in the top 5 of the group
  df_combined.iloc[i+15:i+172, df_combined.columns.get_loc('winning 3')] = '-'

# Print the updated DataFrame
print(df_combined[255:265])

     1  2  3  4  5  6       date 6_number  Draw winning 2 winning 3
255  6  9  6  7  2  9 2024-09-15   696729     2         -         -
256  1  0  8  6  7  8 2024-09-15   108678     2         -         -
257  0  3  2  1  6  1 2024-09-15   032161     2         -         -
258  4  9  3  9  3  7 2024-09-15   493937     2         -         -
259  2  8  7  1  9  0 2024-09-15   287190     2         -         -
260  0  1  2  4  0  1 2024-09-15   012401     2         -         -
261  5  8  9  8  5  4 2024-09-15   589854     2         -         -
262  9  3  5  5  9  9 2024-09-15   935599     2         -         -
263  5  9  0  3  9  5 2024-09-15   590395     2         -         -
264  3  9  7  9  3  2 2024-09-15   397932     2         -         -

In [ ]:
#อันนี้คือแยกรางวัลที่ 4
import pandas as pd

# Assuming your DataFrame is named df_combined

# Create the 'winning 2' column if it doesn't exist
if 'winning 4' not in df_combined.columns:
  df_combined['winning 4'] = ''

for i in range(0, len(df_combined), 172):
  df_combined.iloc[i:i+15, df_combined.columns.get_loc('winning 4')] = '-'
  #The following line was not indented correctly and has been fixed.
  df_combined.iloc[i+15:i+65, df_combined.columns.get_loc('winning 4')] = df_combined.iloc[i+15:i+65]['6_number'].values

  # Set 'winning 2' to '-' for rows that are not in the top 5 of the group
  df_combined.iloc[i+65:i+172, df_combined.columns.get_loc('winning 4')] = '-'

# Print the updated DataFrame
print(df_combined[0:45])

    1  2  3  4  5  6       date 6_number  Draw winning 2 winning 3 winning 4  \
0   6  1  8  3  0  4 2024-10-01   618304     1    618304         -         -
1   7  0  6  5  7  0 2024-10-01   706570     1    706570         -         -
2   9  2  0  2  1  2 2024-10-01   920212     1    920212         -         -
3   6  1  9  4  5  7 2024-10-01   619457     1    619457         -         -
4   8  0  3  1  8  6 2024-10-01   803186     1    803186         -         -
5   0  7  9  5  1  3 2024-10-01   079513     1         -    079513         -
6   8  9  9  1  6  1 2024-10-01   899161     1         -    899161         -
7   0  2  8  9  2  9 2024-10-01   028929     1         -    028929         -
8   0  1  5  0  8  9 2024-10-01   015089     1         -    015089         -
9   5  7  6  8  8  3 2024-10-01   576883     1         -    576883         -
10  8  4  8  7  2  0 2024-10-01   848720     1         -    848720         -
11  3  3  2  5  8  3 2024-10-01   332583     1         -    332583         -
12  8  2  7  6  6  1 2024-10-01   827661     1         -    827661         -
13  9  3  6  7  6  9 2024-10-01   936769     1         -    936769         -
14  8  0  7  5  8  7 2024-10-01   807587     1         -    807587         -
15  4  4  7  7  9  8 2024-10-01   447798     1         -         -    447798
16  3  7  9  5  3  8 2024-10-01   379538     1         -         -    379538
17  0  7  0  4  6  5 2024-10-01   070465     1         -         -    070465
18  1  4  3  8  2  8 2024-10-01   143828     1         -         -    143828
19  5  6  5  2  0  1 2024-10-01   565201     1         -         -    565201
20  1  0  0  5  2  3 2024-10-01   100523     1         -         -    100523
21  7  3  0  4  2  2 2024-10-01   730422     1         -         -    730422
22  6  5  4  7  3  3 2024-10-01   654733     1         -         -    654733
23  3  5  0  9  1  4 2024-10-01   350914     1         -         -    350914
24  9  6  8  2  4  9 2024-10-01   968249     1         -         -    968249
25  7  1  5  9  4  4 2024-10-01   715944     1         -         -    715944
26  9  7  4  0  9  3 2024-10-01   974093     1         -         -    974093
27  0  7  3  7  9  2 2024-10-01   073792     1         -         -    073792
28  3  0  6  4  8  9 2024-10-01   306489     1         -         -    306489
29  3  9  4  7  1  7 2024-10-01   394717     1         -         -    394717
30  8  2  3  3  3  9 2024-10-01   823339     1         -         -    823339
31  3  7  1  5  6  0 2024-10-01   371560     1         -         -    371560
32  2  2  9  3  5  4 2024-10-01   229354     1         -         -    229354
33  5  4  9  7  3  4 2024-10-01   549734     1         -         -    549734
34  5  4  4  3  0  0 2024-10-01   544300     1         -         -    544300
35  7  9  1  3  1  5 2024-10-01   791315     1         -         -    791315
36  6  1  2  1  8  9 2024-10-01   612189     1         -         -    612189
37  5  8  8  5  6  0 2024-10-01   588560     1         -         -    588560
38  7  0  5  1  2  0 2024-10-01   705120     1         -         -    705120
39  1  5  6  0  3  9 2024-10-01   156039     1         -         -    156039
40  0  7  9  2  8  8 2024-10-01   079288     1         -         -    079288
41  9  6  1  7  9  7 2024-10-01   961797     1         -         -    961797
42  3  2  5  6  9  2 2024-10-01   325692     1         -         -    325692
43  2  3  5  4  8  5 2024-10-01   235485     1         -         -    235485
44  0  6  8  7  6  6 2024-10-01   068766     1         -         -    068766

   winning 5 winning 1 winning 1 คล้าย
0          -         -               -
1          -         -               -
2          -         -               -
3          -         -               -
4          -         -               -
5          -         -               -
6          -         -               -
7          -         -               -
8          -         -               -
9          -         -               -
10         -         -               -
11         -         -               -
12         -         -               -
13         -         -               -
14         -         -               -
15         -         -               -
16         -         -               -
17         -         -               -
18         -         -               -
19         -         -               -
20         -         -               -
21         -         -               -
22         -         -               -
23         -         -               -
24         -         -               -
25         -         -               -
26         -         -               -
27         -         -               -
28         -         -               -
29         -         -               -
30         -         -               -
31         -         -               -
32         -         -               -
33         -         -               -
34         -         -               -
35         -         -               -
36         -         -               -
37         -         -               -
38         -         -               -
39         -         -               -
40         -         -               -
41         -         -               -
42         -         -               -
43         -         -               -
44         -         -               -

In [ ]:
#อันนี้คือแยกรางวัลที่ 5
import pandas as pd

# Assuming your DataFrame is named df_combined

# Create the 'winning 5' column if it doesn't exist
if 'winning 5' not in df_combined.columns:
  df_combined['winning 5'] = ''

for i in range(0, len(df_combined), 172):
  df_combined.iloc[i:i+65, df_combined.columns.get_loc('winning 5')] = '-'
  #The following line was not indented correctly and has been fixed.
  df_combined.iloc[i+65:i+165, df_combined.columns.get_loc('winning 5')] = df_combined.iloc[i+65:i+165]['6_number'].values

  # Set 'winning 5' to '-' for rows that are not in the top 5 of the group
  df_combined.iloc[i+165:i+172, df_combined.columns.get_loc('winning 5')] = '-'

# Print the updated DataFrame
print(df_combined[0:56])

    1  2  3  4  5  6       date 6_number  Draw winning 2 winning 3 winning 4  \
0   6  1  8  3  0  4 2024-10-01   618304     1    618304         -         -
1   7  0  6  5  7  0 2024-10-01   706570     1    706570         -         -
2   9  2  0  2  1  2 2024-10-01   920212     1    920212         -         -
3   6  1  9  4  5  7 2024-10-01   619457     1    619457         -         -
4   8  0  3  1  8  6 2024-10-01   803186     1    803186         -         -
5   0  7  9  5  1  3 2024-10-01   079513     1         -    079513         -
6   8  9  9  1  6  1 2024-10-01   899161     1         -    899161         -
7   0  2  8  9  2  9 2024-10-01   028929     1         -    028929         -
8   0  1  5  0  8  9 2024-10-01   015089     1         -    015089         -
9   5  7  6  8  8  3 2024-10-01   576883     1         -    576883         -
10  8  4  8  7  2  0 2024-10-01   848720     1         -    848720         -
11  3  3  2  5  8  3 2024-10-01   332583     1         -    332583         -
12  8  2  7  6  6  1 2024-10-01   827661     1         -    827661         -
13  9  3  6  7  6  9 2024-10-01   936769     1         -    936769         -
14  8  0  7  5  8  7 2024-10-01   807587     1         -    807587         -
15  4  4  7  7  9  8 2024-10-01   447798     1         -         -    447798
16  3  7  9  5  3  8 2024-10-01   379538     1         -         -    379538
17  0  7  0  4  6  5 2024-10-01   070465     1         -         -    070465
18  1  4  3  8  2  8 2024-10-01   143828     1         -         -    143828
19  5  6  5  2  0  1 2024-10-01   565201     1         -         -    565201
20  1  0  0  5  2  3 2024-10-01   100523     1         -         -    100523
21  7  3  0  4  2  2 2024-10-01   730422     1         -         -    730422
22  6  5  4  7  3  3 2024-10-01   654733     1         -         -    654733
23  3  5  0  9  1  4 2024-10-01   350914     1         -         -    350914
24  9  6  8  2  4  9 2024-10-01   968249     1         -         -    968249
25  7  1  5  9  4  4 2024-10-01   715944     1         -         -    715944
26  9  7  4  0  9  3 2024-10-01   974093     1         -         -    974093
27  0  7  3  7  9  2 2024-10-01   073792     1         -         -    073792
28  3  0  6  4  8  9 2024-10-01   306489     1         -         -    306489
29  3  9  4  7  1  7 2024-10-01   394717     1         -         -    394717
30  8  2  3  3  3  9 2024-10-01   823339     1         -         -    823339
31  3  7  1  5  6  0 2024-10-01   371560     1         -         -    371560
32  2  2  9  3  5  4 2024-10-01   229354     1         -         -    229354
33  5  4  9  7  3  4 2024-10-01   549734     1         -         -    549734
34  5  4  4  3  0  0 2024-10-01   544300     1         -         -    544300
35  7  9  1  3  1  5 2024-10-01   791315     1         -         -    791315
36  6  1  2  1  8  9 2024-10-01   612189     1         -         -    612189
37  5  8  8  5  6  0 2024-10-01   588560     1         -         -    588560
38  7  0  5  1  2  0 2024-10-01   705120     1         -         -    705120
39  1  5  6  0  3  9 2024-10-01   156039     1         -         -    156039
40  0  7  9  2  8  8 2024-10-01   079288     1         -         -    079288
41  9  6  1  7  9  7 2024-10-01   961797     1         -         -    961797
42  3  2  5  6  9  2 2024-10-01   325692     1         -         -    325692
43  2  3  5  4  8  5 2024-10-01   235485     1         -         -    235485
44  0  6  8  7  6  6 2024-10-01   068766     1         -         -    068766
45  5  4  9  1  4  3 2024-10-01   549143     1         -         -    549143
46  5  8  5  4  8  7 2024-10-01   585487     1         -         -    585487
47  2  1  4  3  3  9 2024-10-01   214339     1         -         -    214339
48  6  5  6  2  7  8 2024-10-01   656278     1         -         -    656278
49  8  4  9  7  7  8 2024-10-01   849778     1         -         -    849778
50  7  9  5  6  8  7 2024-10-01   795687     1         -         -    795687
51  1  6  6  6  8  5 2024-10-01   166685     1         -         -    166685
52  8  2  7  7  6  6 2024-10-01   827766     1         -         -    827766
53  4  4  8  6  4  8 2024-10-01   448648     1         -         -    448648
54  4  1  5  6  3  1 2024-10-01   415631     1         -         -    415631
55  5  7  9  4  0  4 2024-10-01   579404     1         -         -    579404

   winning 5 winning 1 winning 1 คล้าย
0          -         -               -
1          -         -               -
2          -         -               -
3          -         -               -
4          -         -               -
5          -         -               -
6          -         -               -
7          -         -               -
8          -         -               -
9          -         -               -
10         -         -               -
11         -         -               -
12         -         -               -
13         -         -               -
14         -         -               -
15         -         -               -
16         -         -               -
17         -         -               -
18         -         -               -
19         -         -               -
20         -         -               -
21         -         -               -
22         -         -               -
23         -         -               -
24         -         -               -
25         -         -               -
26         -         -               -
27         -         -               -
28         -         -               -
29         -         -               -
30         -         -               -
31         -         -               -
32         -         -               -
33         -         -               -
34         -         -               -
35         -         -               -
36         -         -               -
37         -         -               -
38         -         -               -
39         -         -               -
40         -         -               -
41         -         -               -
42         -         -               -
43         -         -               -
44         -         -               -
45         -         -               -
46         -         -               -
47         -         -               -
48         -         -               -
49         -         -               -
50         -         -               -
51         -         -               -
52         -         -               -
53         -         -               -
54         -         -               -
55         -         -               -

In [ ]:
#อันนี้คือแยกรางวัลที่ 1
import pandas as pd

# Assuming your DataFrame is named df_combined

# Create the 'winning 2' column if it doesn't exist
if 'winning 1' not in df_combined.columns:
  df_combined['winning 1'] = ''

for i in range(0, len(df_combined), 172):
  df_combined.iloc[i:i+171, df_combined.columns.get_loc('winning 1')] = '-'
  #The following line was not indented correctly and has been fixed.
  df_combined.iloc[i+171:i+172, df_combined.columns.get_loc('winning 1')] = df_combined.iloc[i+171:i+172]['6_number'].values


# Print the updated DataFrame
print(df_combined[171:172])

     1  2  3  4  5  6       date 6_number  Draw winning 2 winning 3 winning 4  \
171  7  1  8  6  6  5 2024-10-01   718665     1         -         -         -

    winning 5 winning 1
171         -    718665

In [ ]:
#อันนี้คือแยกรางวัลที่คล้ายที่ 1
import pandas as pd

# Assuming your DataFrame is named df_combined

# Create the 'winning 2' column if it doesn't exist
if 'winning 1 คล้าย' not in df_combined.columns:
  df_combined['winning 1 คล้าย'] = ''

for i in range(0, len(df_combined), 172):
  df_combined.iloc[i:i+169, df_combined.columns.get_loc('winning 1 คล้าย')] = '-'
  #The following line was not indented correctly and has been fixed.
  df_combined.iloc[i+169:i+171, df_combined.columns.get_loc('winning 1 คล้าย')] = df_combined.iloc[i+169:i+171]['6_number'].values

  # Set 'winning 2' to '-' for rows that are not in the top 5 of the group
  df_combined.iloc[i+171:i+172, df_combined.columns.get_loc('winning 1 คล้าย')] = '-'

# Print the updated DataFrame
print(df_combined[0:56])

    1  2  3  4  5  6       date 6_number  Draw winning 2 winning 3 winning 4  \
0   6  1  8  3  0  4 2024-10-01   618304     1    618304         -         -
1   7  0  6  5  7  0 2024-10-01   706570     1    706570         -         -
2   9  2  0  2  1  2 2024-10-01   920212     1    920212         -         -
3   6  1  9  4  5  7 2024-10-01   619457     1    619457         -         -
4   8  0  3  1  8  6 2024-10-01   803186     1    803186         -         -
5   0  7  9  5  1  3 2024-10-01   079513     1         -    079513         -
6   8  9  9  1  6  1 2024-10-01   899161     1         -    899161         -
7   0  2  8  9  2  9 2024-10-01   028929     1         -    028929         -
8   0  1  5  0  8  9 2024-10-01   015089     1         -    015089         -
9   5  7  6  8  8  3 2024-10-01   576883     1         -    576883         -
10  8  4  8  7  2  0 2024-10-01   848720     1         -    848720         -
11  3  3  2  5  8  3 2024-10-01   332583     1         -    332583         -
12  8  2  7  6  6  1 2024-10-01   827661     1         -    827661         -
13  9  3  6  7  6  9 2024-10-01   936769     1         -    936769         -
14  8  0  7  5  8  7 2024-10-01   807587     1         -    807587         -
15  4  4  7  7  9  8 2024-10-01   447798     1         -         -    447798
16  3  7  9  5  3  8 2024-10-01   379538     1         -         -    379538
17  0  7  0  4  6  5 2024-10-01   070465     1         -         -    070465
18  1  4  3  8  2  8 2024-10-01   143828     1         -         -    143828
19  5  6  5  2  0  1 2024-10-01   565201     1         -         -    565201
20  1  0  0  5  2  3 2024-10-01   100523     1         -         -    100523
21  7  3  0  4  2  2 2024-10-01   730422     1         -         -    730422
22  6  5  4  7  3  3 2024-10-01   654733     1         -         -    654733
23  3  5  0  9  1  4 2024-10-01   350914     1         -         -    350914
24  9  6  8  2  4  9 2024-10-01   968249     1         -         -    968249
25  7  1  5  9  4  4 2024-10-01   715944     1         -         -    715944
26  9  7  4  0  9  3 2024-10-01   974093     1         -         -    974093
27  0  7  3  7  9  2 2024-10-01   073792     1         -         -    073792
28  3  0  6  4  8  9 2024-10-01   306489     1         -         -    306489
29  3  9  4  7  1  7 2024-10-01   394717     1         -         -    394717
30  8  2  3  3  3  9 2024-10-01   823339     1         -         -    823339
31  3  7  1  5  6  0 2024-10-01   371560     1         -         -    371560
32  2  2  9  3  5  4 2024-10-01   229354     1         -         -    229354
33  5  4  9  7  3  4 2024-10-01   549734     1         -         -    549734
34  5  4  4  3  0  0 2024-10-01   544300     1         -         -    544300
35  7  9  1  3  1  5 2024-10-01   791315     1         -         -    791315
36  6  1  2  1  8  9 2024-10-01   612189     1         -         -    612189
37  5  8  8  5  6  0 2024-10-01   588560     1         -         -    588560
38  7  0  5  1  2  0 2024-10-01   705120     1         -         -    705120
39  1  5  6  0  3  9 2024-10-01   156039     1         -         -    156039
40  0  7  9  2  8  8 2024-10-01   079288     1         -         -    079288
41  9  6  1  7  9  7 2024-10-01   961797     1         -         -    961797
42  3  2  5  6  9  2 2024-10-01   325692     1         -         -    325692
43  2  3  5  4  8  5 2024-10-01   235485     1         -         -    235485
44  0  6  8  7  6  6 2024-10-01   068766     1         -         -    068766
45  5  4  9  1  4  3 2024-10-01   549143     1         -         -    549143
46  5  8  5  4  8  7 2024-10-01   585487     1         -         -    585487
47  2  1  4  3  3  9 2024-10-01   214339     1         -         -    214339
48  6  5  6  2  7  8 2024-10-01   656278     1         -         -    656278
49  8  4  9  7  7  8 2024-10-01   849778     1         -         -    849778
50  7  9  5  6  8  7 2024-10-01   795687     1         -         -    795687
51  1  6  6  6  8  5 2024-10-01   166685     1         -         -    166685
52  8  2  7  7  6  6 2024-10-01   827766     1         -         -    827766
53  4  4  8  6  4  8 2024-10-01   448648     1         -         -    448648
54  4  1  5  6  3  1 2024-10-01   415631     1         -         -    415631
55  5  7  9  4  0  4 2024-10-01   579404     1         -         -         -

   winning 5 winning 1 winning 1 คล้าย
0          -         -               -
1          -         -               -
2          -         -               -
3          -         -               -
4          -         -               -
5          -         -               -
6          -         -               -
7          -         -               -
8          -         -               -
9          -         -               -
10         -         -               -
11         -         -               -
12         -         -               -
13         -         -               -
14         -         -               -
15         -         -               -
16         -         -               -
17         -         -               -
18         -         -               -
19         -         -               -
20         -         -               -
21         -         -               -
22         -         -               -
23         -         -               -
24         -         -               -
25         -         -               -
26         -         -               -
27         -         -               -
28         -         -               -
29         -         -               -
30         -         -               -
31         -         -               -
32         -         -               -
33         -         -               -
34         -         -               -
35         -         -               -
36         -         -               -
37         -         -               -
38         -         -               -
39         -         -               -
40         -         -               -
41         -         -               -
42         -         -               -
43         -         -               -
44         -         -               -
45         -         -               -
46         -         -               -
47         -         -               -
48         -         -               -
49         -         -               -
50         -         -               -
51         -         -               -
52         -         -               -
53         -         -               -
54         -         -               -
55    579404         -               -

In [ ]:
#อันนี้คือ 3 ตัวหน้า
import pandas as pd

# Assuming your DataFrame is named df_combined

# Create the 'winning 2' column if it doesn't exist
if 'First 3 numbers' not in df_combined.columns:
  df_combined['First 3 numbers'] = ''

for i in range(0, len(df_combined), 172):
  df_combined.iloc[i:i+165, df_combined.columns.get_loc('First 3 numbers')] = '-'
  #The following line was not indented correctly and has been fixed.
  df_combined.iloc[i+165:i+167, df_combined.columns.get_loc('First 3 numbers')] = df_combined.iloc[i+165:i+167]['1'].astype(str).str.zfill(1) + df_combined.iloc[i+165:i+167]['2'].astype(str) +df_combined.iloc[i+165:i+167]['3'].astype(str)

  # Set 'winning 2' to '-' for rows that are not in the top 5 of the group
  df_combined.iloc[i+167:i+172, df_combined.columns.get_loc('First 3 numbers')] = '-'

# Print the updated DataFrame
print(df_combined[162:167])

     1  2  3  4  5  6        date 6_number  Draw winning 2 winning 3  \
162  4  4  7  1  4  2  2024-10-01   447142     1         -         -
163  5  1  1  9  8  9  2024-10-01   511989     1         -         -
164  3  4  2  3  8  4  2024-10-01   342384     1         -         -
165  0  5  3  0  0  0  2024-10-01   053000     1         -         -
166  8  1  2  0  0  0  2024-10-01   812000     1         -         -

    winning 4 winning 5 winning 1 winning 1 คล้าย First 3 numbers
162         -    447142         -               -               -
163         -    511989         -               -               -
164         -    342384         -               -               -
165         -         -         -               -             053
166         -         -         -               -             812

In [ ]:
#อันนี้คือ 3 ตัวหลัง
import pandas as pd

# Assuming your DataFrame is named df_combined

# Create the 'winning 2' column if it doesn't exist
if 'last 2 numbers' not in df_combined.columns:
  df_combined['last 2 numbers'] = ''

for i in range(0, len(df_combined), 172):
  df_combined.iloc[i:i+167, df_combined.columns.get_loc('last 2 numbers')] = '-'
  #The following line was not indented correctly and has been fixed.
  df_combined.iloc[i+167:i+169, df_combined.columns.get_loc('last 2 numbers')] = df_combined.iloc[i+167:i+169]['4'].astype(str).str.zfill(1) + df_combined.iloc[i+167:i+169]['5'].astype(str) + df_combined.iloc[i+167:i+169]['6'].astype(str)

  # Set 'winning 2' to '-' for rows that are not in the top 5 of the group
  df_combined.iloc[i+169:i+172, df_combined.columns.get_loc('last 2 numbers')] = '-'

# Print the updated DataFrame
print(df_combined[167:172])

     1  2  3  4  5  6        date 6_number  Draw winning 2 winning 3  \
167  0  0  0  0  7  9  2024-10-01   000079     1         -         -
168  0  0  0  5  6  6  2024-10-01   000566     1         -         -
169  7  1  8  6  6  4  2024-10-01   718664     1         -         -
170  7  1  8  6  6  6  2024-10-01   718666     1         -         -
171  7  1  8  6  6  5  2024-10-01   718665     1         -         -

    winning 4 winning 5 winning 1 winning 1 คล้าย First 3 numbers  \
167         -         -         -               -               -
168         -         -         -               -               -
169         -         -         -          718664               -
170         -         -         -          718666               -
171         -         -    718665               -               -

    last 2 numbers
167            079
168            566
169              -
170              -
171              -

In [ ]:
import pandas as pd
PrepDF= pd.read_csv('Prep_data_lottery.csv')

In [ ]:
print(df_combined[165:192])

     1  2  3  4  5  6 6_number       date  Draw winning 2
165  0  5  3  0  0  0   053000 2024-10-01     1    803186
166  8  1  2  0  0  0   812000 2024-10-01     1    803186
167  0  0  0  0  7  9   000079 2024-10-01     1    803186
168  0  0  0  5  6  6   000566 2024-10-01     1    803186
169  7  1  8  6  6  4   718664 2024-10-01     1    803186
170  7  1  8  6  6  6   718666 2024-10-01     1    803186
171  7  1  8  6  6  5   718665 2024-10-01     1    803186

In [ ]:
DF5 = df_combined

In [ ]:

DF5.to_csv('prep_data_loterry.csv', index=False)

##Function  ตรวจหวยที่ผ่านมาทั้งหมด 5 ปี

In [ ]:
import pandas as pd

def inspect_number():
  df = df_combined
  number = input("Enter a number: ")
  """
  This function inspects a number against a DataFrame to find matches, displays
  results as a DataFrame, including the matching numbers, and checks if the
  first 3 and last 3 digits match specific columns.

  Args:
    df: The DataFrame to inspect.
    number: The number to inspect.

  Returns:
    A DataFrame containing the date, frequency, and matching numbers for
    full, first 3 digits, and last 3 digits matches.
  """

  # Convert the number to a string
  number = str(number)

  # Check if the number matches any values in the '6_number' column
  matches = df[df['6_number'] == number]

  # Check if the first 3 numbers match any values in the 'First 3 numbers' column
  first_3_matches = df[df['First 3 numbers'] == number[:3]]

  # Check if the last 3 numbers match any values in the 'last 3 numbers' column
  last_3_matches = df[df['last 2 numbers'] == number[-3:]]

  if not matches.empty or not first_3_matches.empty or not last_3_matches.empty:

    # Get the dates, frequency, and matching numbers for the 6-digit matches
    dates = matches['date'].values.tolist()
    freq = len(matches)
    matched_numbers = matches['6_number'].values.tolist()

    # Get the dates, frequency, and matching numbers for the first 3-digit matches
    first_3_dates = first_3_matches['date'].values.tolist()
    first_3_freq = len(first_3_matches)
    first_3_matched_numbers = first_3_matches['6_number'].values.tolist()

    # Get the dates, frequency, and matching numbers for the last 3-digit matches
    last_3_dates = last_3_matches['date'].values.tolist()
    last_3_freq = len(last_3_matches)
    last_3_matched_numbers = last_3_matches['6_number'].values.tolist()

    # Create a dictionary for the DataFrame data
    data = {
        "Date(s) - 6 digits": [', '.join(dates)],
        "Frequency - 6 digits": [freq],
        "Matched Numbers - 6 digits": [', '.join(matched_numbers)],
        "Date(s) - First 3 digits": [', '.join(first_3_dates)],
        "Frequency - First 3 digits": [first_3_freq],
        "Matched Numbers - First 3 digits": [', '.join(first_3_matched_numbers)],
        "Date(s) - Last 3 digits": [', '.join(last_3_dates)],
        "Frequency - Last 3 digits": [last_3_freq],
        "Matched Numbers - Last 3 digits": [', '.join(last_3_matched_numbers)],
    }

    # Return the results as a DataFrame
    return pd.DataFrame(data)

  else:
    return "Your number did not match any entries in the DataFrame."

In [ ]:
inspect_number()

Enter a number: 935619

'Your number did not match any entries in the DataFrame.'

## This is Running loop section

In [ ]:
##text Data set
all_lottery_data = []

In [ ]:
#Runner loop section

import pandas as pd
from gazpacho import get, Soup

url = "https://www.thairath.co.th/lottery/check?date=2018-12-30"
html = get(url)
soup = Soup(html)
# Find the <p> element with the specified class
elements = soup.find('p', {'class': 'css-pnpogb ecgl95t18'})

for element in elements:
        lottery_number = element.text
        # Create a dictionary to store the lottery number with separate positions
        lottery_data = {'1': lottery_number[0],
                        '2': lottery_number[1],
                        '3': lottery_number[2],
                        '4': lottery_number[3],
                        '5': lottery_number[4],
                        '6': lottery_number[5]}

        all_lottery_data.append(lottery_data) # Append each lottery_data to the list

elements = soup.find('p', {'class': "css-jf9pru ecgl95t12"})

# Counter for the loop
count = 0

for element in elements:
    lottery_number = element.text

    if count < 2:
        # Add "0" after the number
        modified_number = lottery_number + "000"
        count += 1
    else:
        # Use zfill(6)
        modified_number = lottery_number.zfill(6)

    lottery_data_2 = {'1': modified_number[0],
                    '2': modified_number[1],
                    '3': modified_number[2],
                    '4': modified_number[3],
                    '5': modified_number[4],
                    '6': modified_number[5]}

    all_lottery_data.append(lottery_data_2)
elements = soup.find('p', {'class': "css-1uk1gs8 ecgl95t7"})

lottery_number = ""  # Initialize an empty string to store the combined numbers

for element in elements:
    lottery_number += element.text  # Concatenate the numbers from each element

# Corrected indentation for the following block
lottery_data_3 = {'1': lottery_number[0],
                  '2': lottery_number[1],
                  '3': lottery_number[2],
                  '4': lottery_number[3],
                  '5': lottery_number[4],
                  '6': lottery_number[5]}
all_lottery_data.append(lottery_data_3)
##View df section
df_real = pd.DataFrame(all_lottery_data) # Create the DataFrame outside the loop
print(df_real)
df.to_csv('update_lottery_numbers.csv', index=False)

In [ ]:
##View df section
df = pd.DataFrame(all_lottery_data) # Create the DataFrame outside the loop
print(df)
df.to_csv('lottery_numbers.csv', index=False)

       1  2  3  4  5  6
0      4  7  4  5  1  0
1      5  4  4  9  7  8
2      7  0  5  4  3  2
3      9  1  0  6  2  7
4      8  4  1  6  8  2
...   .. .. .. .. .. ..
23215  0  0  0  7  0  1
23216  0  0  0  8  8  4
23217  7  3  5  8  6  6
23218  7  3  5  8  6  8
23219  7  3  5  8  6  7

[23220 rows x 6 columns]

In [ ]:
# prompt: how to import csv

import pandas as pd

# Replace 'your_file.csv' with the actual path to your CSV file
DF_data_lottery = pd.read_csv('lottery_numbers 5 years ago.csv')
print(DF_data_lottery)

       1  2  3  4  5  6
0      4  7  4  5  1  0
1      5  4  4  9  7  8
2      7  0  5  4  3  2
3      9  1  0  6  2  7
4      8  4  1  6  8  2
...   .. .. .. .. .. ..
23215  0  0  0  7  0  1
23216  0  0  0  8  8  4
23217  7  3  5  8  6  6
23218  7  3  5  8  6  8
23219  7  3  5  8  6  7

[23220 rows x 6 columns]

## Trying to learn Machine Learning Section

In [ ]:
import pandas as pd
TD = pd.read_csv('titanic_data.csv')
TD.shape
TD.isnull().sum()
import numpy as np
from sklearn.impute import SimpleImputer
age = TD["Age"].values
age = np.reshape(age,(-1,1))
age_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
age_imputer.fit(age)
age = age_imputer.transform(age)
age = np.ravel(age)
TD["Age"] = age
TD.isnull().sum()
TD.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

# Assuming TD is your DataFrame
imp = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=0)
# Convert the DataFrame to a NumPy array
TD_array = imp.fit_transform(TD)
# Convert the NumPy array back to a Pandas DataFrame
TD = pd.DataFrame(TD_array, columns=TD.columns) # Ensure column names are preserved
TD.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
X = TD[['Pclass','Fare']]
print(X.head())
Y = TD[['Survived']]
Y.head()
Y.shape

  Pclass     Fare
0      3     7.25
1      1  71.2833
2      3    7.925
3      1     53.1
4      3     8.05

(891, 1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(623, 2)
(268, 2)
(623, 1)
(268, 1)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
# Convert Y_train to a 1D array or Series
# Ensure the 'Survived' column is of integer type
Y_train['Survived'] = Y_train['Survived'].astype(int)
model.fit(X_train, Y_train['Survived'].values.ravel()) # Access the 'Survived' column as a Series

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(Y_test['Survived'].astype(int), y_pred)

0.6940298507462687

In [ ]:
ans = model.predict_proba([[3,0]])
ans[:]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[0.75802156, 0.24197844]])

In [ ]:
# Calculate the standard deviation for numeric columns only
TD[['Pclass','Fare','Survived','Age']].describe()

        Pclass    Fare  Survived         Age
count      891  891.00       891  891.000000
unique       3  248.00         2   89.000000
top          3    8.05         0   29.699118
freq       491   43.00       549  177.000000

In [ ]:
# Convert 'Pclass' and 'Survived' to numeric type, if they are not already
TD['Pclass'] = pd.to_numeric(TD['Pclass'])
TD['Survived'] = pd.to_numeric(TD['Survived'])
TD['Age'] = pd.to_numeric(TD['Age'])
TD['Fare'] = pd.to_numeric(TD['Fare'])
# Now calculate the descriptive statistics
TD[['Pclass', 'Fare', 'Survived', 'Age']].describe()

           Pclass        Fare    Survived         Age
count  891.000000  891.000000  891.000000  891.000000
mean     2.308642   32.204208    0.383838   29.699118
std      0.836071   49.693429    0.486592   13.002015
min      1.000000    0.000000    0.000000    0.420000
25%      2.000000    7.910400    0.000000   22.000000
50%      3.000000   14.454200    0.000000   29.699118
75%      3.000000   31.000000    1.000000   35.000000
max      3.000000  512.329200    1.000000   80.000000

In [ ]:
ans = model.predict_proba([[2.32,32.204208]])
ans[:]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[0.63252201, 0.36747799]])

In [ ]:
ans = model.predict_proba([[1,300]])
ans[:]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[0.149145, 0.850855]])

In [ ]:
TD = pd.concat([TD,pd.get_dummies(TD['Sex'], prefix = 'Sex',
                                  dummy_na = True)],axis=1).drop(['Sex'],axis=1)
TD.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male,Sex_nan
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,0,S,False,True,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,0,S,True,False,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,True,False,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,0,S,False,True,False

In [ ]:
X = TD[['Pclass','Fare','Sex_female','Sex_male']]
y = TD['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7910447761194029

In [ ]:
from sklearn.metrics import confusion_matrix # import the module

conf = confusion_matrix(y_test, y_pred) # call the function directly from the module
print('                 Confusion matrix')
print('                          Survie           Die   ')
print('Actual Survie      %6d' % conf[0,0] + '            %5d' % conf[0,1] )
print('Actual Die          %6d' % conf[1,0] + '            %5d' % conf[1,1] )

                 Confusion matrix
                          Survie           Die
Actual Survie         134               23
Actual Die              33               78